kind: Job
apiVersion: batch/v1
metadata:
  name: demo-job
  namespace: nginx
spec:
  completions: 1 # Number of successful completions required
  parallelism: 1 # Number of pods to run in parallel
  template:
    metadata:
      name: demo-job-pod
      labels:
        app: batch-task

    spec:
      containers:
      - name: batch-container
        image: busybox:latest 
        command: ["sh", "-c", "echo 'Hello, Kubernetes!' && sleep 30"]
      restartPolicy: Never       