apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prod-pvc
  labels:
    environment: production
spec:
  accessModes:
    - ReadWriteOnce # Allows the volume to be mounted as read-write by a single node
  storageClassName: high-performance
  resources:
    requests:
      storage: 20Gi
