apiVersion: v1
kind: Service
metadata:
  name: apache-nodeport
  namespace: service-ns
spec:
  type: NodePort
  selector:
    app: apache
  ports:
    - port: 80        # Service port
      targetPort: 80  # Container port
      #nodePort: 30080 # External port